version: '3'

services:
    db:
        image: postgis/postgis:15-3.3
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - ./.env.production

    web:
        build:
            context: .
            dockerfile: ./deploy/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/tfkt
        ports:
            - "8000:8000"
        env_file:
            - ./.env.production
        depends_on:
            - db

volumes:
    db_data: