# Generated by Django 4.2.3 on 2023-07-29 00:43

from django.db import migrations, models
import utils.file_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=32, null=True)),
                (
                    "description",
                    models.CharField(default=None, max_length=128, null=True),
                ),
                ("rules", models.JSONField(default=None, null=True)),
                ("start_date", models.DateField(default=None, null=True)),
                ("end_date", models.DateField(default=None, null=True)),
                (
                    "cover_photo",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to=utils.file_utils.challenge_directory_path,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
